# This is a basic workflow to help you get started with Actions

name: Create Pull Request to staging branch

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  # schedule:
  #   - "0 1 * * 3" # 毎週水曜日の10時にPRの作成
  push:
    branches:
      - ci/githubactions

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Get current
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout Staging branch
        uses: actions/checkout@v2
        with:
          ref: staging # PRのBaseになる

      # - name: Fetch develop branch
      #   run: |
      #     git fetch origin develop:develop
      #     git reset --hard develop

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          author: GitHub <noreply@github.com>
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          title: "${{steps.date.outputs.date}} For Release"
          base: staging
          branch: develop
          reviewers: |
            taku-nakagawa-developer

      - name: Check Outputs
        id: co
        run: |
          echo "::set-output name=url::$()"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

      - name: Notify Create PR
        uses: 8398a7/action-slack@v3.9.0
        if: steps.cpr.outputs.pull-request-url != ''
        with:
          status: ${{ job.status }}
          mention: here
          fields: repo
          text: |
            PR URL - ${{ steps.cpr.outputs.pull-request-url }}
            確認後、Approvalをしてください
          icon_emoji: ":wink:"
          author_name: "auto create pr"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Not Create PR
        uses: 8398a7/action-slack@v3.9.0
        if: steps.cpr.outputs.pull-request-url == ''
        with:
          status: ${{ job.status }}
          mention: here
          fields: repo
          text: |
            下記のブランチでは差分はないです
            リリースはなしです。
          icon_emoji: ":wink:"
          author_name: "auto create pr"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
